name: expense_tracker
description: "A lightweight expense tracking mobile application with Clean Architecture, BLoC, and Hive"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Networking
  http: ^1.1.0
  dio: ^5.3.2

  # File Handling
  image_picker: ^1.0.4
  pdf: ^3.10.4
  csv: ^5.0.2
  share_plus: ^7.2.1
  permission_handler: ^11.1.0

  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  dartz: ^0.10.1

  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0

  # Navigation
  go_router: ^14.2.7
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
