name: PR Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Check formatting
      run: dart format --set-exit-if-changed . || echo "Formatting issues found but not failing build"
      
    - name: Analyze code
      run: flutter analyze --no-fatal-infos
      continue-on-error: true
      
    - name: Run tests
      run: flutter test
      
    - name: Check build
      run: flutter build apk --debug 